# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustytools_wrappers", use_symbols = TRUE, package_name = "rustytools")

#' @docType package
#' @usage NULL
#' @useDynLib rustytools, .registration = TRUE
NULL

test_conversion <- function(x) .Call(wrap__test_conversion, x)

#' @export
diffuse_expr_r <- function(p, x, t, chunk) .Call(wrap__diffuse_expr_r, p, x, t, chunk)

#' @export
getconsensus <- function(rstring, index_add) .Call(wrap__getconsensus, rstring, index_add)

#' @export
align_rust <- function(rstring1, rstring2, atype, verbose) .Call(wrap__align_rust, rstring1, rstring2, atype, verbose)

#' @export
pcha_rust <- function(input_mat, k, c_init, s_init, max_iter_arg, conv_crit_arg) .Call(wrap__pcha_rust, input_mat, k, c_init, s_init, max_iter_arg, conv_crit_arg)


# nolint end
