# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustytools_wrappers", use_symbols = TRUE, package_name = "rustytools")

#' @docType package
#' @usage NULL
#' @useDynLib rustytools, .registration = TRUE
NULL

test_conversion <- function(x) .Call(wrap__test_conversion, x)

#' @export
diffuse_expr_r <- function(p, x, t, chunk) .Call(wrap__diffuse_expr_r, p, x, t, chunk)

#' @export
getconsensus <- function(rstring, index_add) .Call(wrap__getconsensus, rstring, index_add)

#' @export
align_rust <- function(rstring1, rstring2, atype, verbose) .Call(wrap__align_rust, rstring1, rstring2, atype, verbose)

#' Call PCHA from R
#'
#' @param input_mat   numeric matrix (variables in rows, samples in columns)
#' @param noc   integer, number of archetypes/components
#' @return list of matrices
#' @export
pcha <- function(input_mat, noc) .Call(wrap__pcha, input_mat, noc)


# nolint end
